---
- name: Include add users
  include_tasks: 
    file: "add_users.yml"
    apply:
      tags: add_users
  tags:
    - add_users
- name: Include update tasks
  include_tasks: 
    file: "node_exporter.yml"
    apply:
      tags: node_exporter
  tags:
    - node_exporter
- name: Include update sshd
  include_tasks: 
    file: "update_sshd.yml"
    apply:
      tags: update_sshd
  tags:
    - update_sshd
