---
- name: Install the present version of Apache and MariaDB
  package:
    name:
      - build-essential
      - libmp3lame-dev
      - libshout3-dev
      - libconfig++-dev
      - libraspberrypi-dev
      - librtlsdr-dev
      - libpulse-dev
      - git
      - rtl-sdr
    state: present
  become: true
- name: Git checkout
  git:
    repo: 'https://github.com/szpajder/RTLSDR-Airband.git'
    dest: /srv/rtlsdr-airband
    version: v3.2.1
  become: true
- name: Make
  make:
    chdir: /srv/rtlsdr-airband
    params:
      PLATFORM: rpiv2
      NFM: 1
  become: true
- name: Make install
  make:
    chdir: /srv/rtlsdr-airband
    target: install
  become: true
- name: copy the config file
  template:
    src: rtlsdr-airband.j2
    dest: /usr/local/etc/rtl_airband.conf
    mode: '0755'
  become: true
- name: Copy file with owner and permissions
  copy:
    src: /srv/rtlsdr-airband/init.d/rtl_airband.service
    dest: /etc/systemd/system/rtl_airband.service
    owner: root
    group: root
    mode: '0755'
    remote_src: true
  become: true
- name: Reload, enable, and start rtl_airband
  systemd:
    state: restarted
    daemon_reload: true
    enabled: true
    name: rtl_airband
  become: true
