volumes:
  ultrafeeder_globe_history:
  ultrafeeder_graphs1090:

services:
  piaware:
    image: ghcr.io/sdr-enthusiasts/docker-piaware:latest
    tty: true
    container_name: piaware
    restart: always
    depends_on:
      - ultrafeeder
    ports:
      - 8081:80
    environment:
      - TZ=${FEEDER_TZ}
      - LAT=${FEEDER_LAT}
      - LONG=${FEEDER_LONG}
      - RECEIVER_TYPE=relay
      - BEASTHOST=ultrafeeder
      - BEASTPORT=30005
      - FEEDER_ID=${piaware_UUID}
    tmpfs:
      - /run:exec,size=64M
      - /var/log

  ultrafeeder:
    image: ghcr.io/sdr-enthusiasts/docker-adsb-ultrafeeder
    tty: true
    container_name: ultrafeeder
    hostname: ultrafeeder
    restart: unless-stopped
    device_cgroup_rules:
      - 'c 189:* rwm'
    ports:
      - 8080:80               # to expose the web interface
      - 9273-9274:9273-9274   # to expose the statistics interface to Prometheus
      - 30105:30105
      - 31005:31005
      - 30005:30005
      - 31006:31006
      - 30006:30006
    environment:
      # --------------------------------------------------
      # general parameters:
      - LOGLEVEL=error
      - TZ=${FEEDER_TZ}
      # --------------------------------------------------
      # SDR related parameters:
      - READSB_DEVICE_TYPE=rtlsdr
      - READSB_RTLSDR_DEVICE=${ADSB_SDR_SERIAL}
      - READSB_RTLSDR_PPM=${ADSB_SDR_PPM}
      #
      # --------------------------------------------------
      # readsb/decoder parameters:
      - READSB_LAT=${FEEDER_LAT}
      - READSB_LON=${FEEDER_LONG}
      - READSB_ALT=${FEEDER_ALT_M}m
      - READSB_GAIN=${ADSB_SDR_GAIN}
      - READSB_MODEAC=true
      - READSB_RX_LOCATION_ACCURACY=2
      - READSB_STATS_RANGE=true
      #
      # --------------------------------------------------
      # Sources and Aggregator connections:
      # (Note - remove the ones you are not using / feeding)
      - READSB_NET_CONNECTOR=
          piaware,30105,beast_in;
          feed.adsb.fi,30004,beast_reduce_plus_out;
          in.adsb.lol,30004,beast_reduce_plus_out;
          feed.adsb.one,64004,beast_reduce_plus_out;
          feed.planespotters.net,30004,beast_reduce_plus_out;
          feed1.adsbexchange.com,30004,beast_reduce_plus_out
      # If you really want to feed ADSBExchange, you can do so by adding this above: feed1.adsbexchange.com,30004,beast_reduce_plus_out
      - UUID=${MULTIFEEDER_UUID}
      #
      # --------------------------------------------------
      # MLAT and MLATHUB related parameters:
      # MLAT_CONFIG defines who you are feeding MLAT data to, and on what port(s) the results will become available
      - MLAT_CONFIG=
          feed.adsb.fi,31090,39000;
          in.adsb.lol,31090,39001;
          feed.adsb.one,64006,39002;
          mlat.planespotters.net,31090,39003;
          feed.adsbexchange.com,31090,39005
      # If you really want to feed ADSBExchange, you can do so by adding this above: feed.adsbexchange.com,31090,39005
      - MLAT_USER=${FEEDER_NAME}
      # MLATHUB automatically gets MLAT results data from the feeders defined in MLAT_CONFIG,
      # and additionally from the Net Connectors defined with MLATHUB_NET_CONNECTOR
      - MLATHUB_NET_CONNECTOR=
          piaware,30104,beast_in
      #    rbfeeder,30105,beast_in;
      #    radarvirtuel,30105,beast_in
      - MLATHUB_BEAST_OUT_PORT=31005
      #
      # --------------------------------------------------
      # TAR1090 (Map Web Page) parameters:
      - UPDATE_TAR1090=true
      - TAR1090_DEFAULTCENTERLAT=${FEEDER_LAT}
      - TAR1090_DEFAULTCENTERLON=${FEEDER_LONG}
      - TAR1090_MESSAGERATEINTITLE=true
      - TAR1090_PAGETITLE=${FEEDER_NAME}
      - TAR1090_PLANECOUNTINTITLE=true
      - TAR1090_ENABLE_AC_DB=true
      - TAR1090_FLIGHTAWARELINKS=true
      - HEYWHATSTHAT_PANORAMA_ID=${FEEDER_HEYWHATSTHAT_ID}
      - HEYWHATSTHAT_ALTS=${FEEDER_HEYWHATSTHAT_ALTS}
      - TAR1090_SITESHOW=true
      - TAR1090_RANGE_OUTLINE_COLORED_BY_ALTITUDE=true
      - TAR1090_RANGE_OUTLINE_WIDTH=2.0
      - TAR1090_RANGERINGSDISTANCES=50,100,150,200
      - TAR1090_RANGERINGSCOLORS='#1A237E','#0D47A1','#42A5F5','#64B5F6'
      #
      # --------------------------------------------------
      # GRAPHS1090 (Decoder and System Status Web Page) parameters:
      # The two 978 related parameters should only be included if you are running dump978 for UAT reception (USA only)
      - GRAPHS1090_DARKMODE=true
      # - ENABLE_978=no
      # - URL_978=
      # 
      # --------------------------------------------------
      # Prometheus and InfluxDB connection parameters:
      - INFLUXDBV2_URL=${INFLUX_URL}
      - INFLUXDBV2_TOKEN=${INFLUX_TOKEN}
      - INFLUXDBV2_BUCKET=${INFLUX_BUCKET}
      - PROMETHEUS_ENABLE=true
    volumes:
      - ultrafeeder_globe_history:/var/globe_history
      - ultrafeeder_graphs1090:/var/lib/collectd
      - /proc/diskstats:/proc/diskstats:ro
      - /dev/bus/usb:/dev/bus/usb:rw
    # Below read only did not work on this pi, but I have used it in other situations... So RW above - Sam
    #  - /dev:/dev:ro
    tmpfs:
      - /run:exec,size=256M
      - /tmp:size=128M
      - /var/log:size=32M

