---
ingress: 
  enabled: true
  hosts: 
    - "speedtest.k8s.leb.memhamwan.net"
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: speedtest-tls
      hosts:
        - speedtest.k8s.leb.memhamwan.net