---
- name: Include update tasks
  include_tasks:
    file: "update.yaml"
    apply:
      tags:
        - update
  tags:
    - update
- name: Include harden tasks
  include_tasks:
    file: "harden.yaml"
    apply:
      tags:
        - harden
  tags:
    - harden
- name: Include user_subnets tasks
  include_tasks:
    file: "user_subnets.yaml"
    apply:
      tags:
        - user_subnets
  loop: "{{ user_subnets }}"
  when: "user_subnets is defined"
  tags:
    - user_subnets
- name: Get list of users on live
  community.network.routeros_command:
    commands:
      - ":foreach i in=[ /user print as-value ] do={:put ($i->\"name\")}"
  register: existing_users_raw
  tags:
    - add-users
- name: Parse ROS output and set existing_users variable
  set_fact:
    existing_users: "{{ existing_users_raw.stdout[0].split('\n\n')[1].split('\n') }}"
  tags:
    - add-users
- name: Setup netops users
  include_tasks:
    file: "add_netops.yml"
    apply:
      tags:
        - add-users
  loop: "{{ users }}"
  tags:
    - add-users
