---
- name: Get list of bridge interfaces
  community.network.routeros_command:
    commands: "/interface bridge export"
  register: get_bridge_results

- name: Add the bridge interface
  community.network.routeros_command:
    commands: "/interface bridge add name={{ item.name }}"
  register: add_bridge_results
  failed_when: "'failure' in add_bridge_results.stdout[0]"
  when: get_bridge_results.stdout[0].find("name="+item.name+"\n") == -1
  changed_when: true

- name: Get list of IP addresses
  community.network.routeros_command:
    commands: "/ip address export"
  register: get_address_results

- name: Add the IP address
  community.network.routeros_command:
    commands: "/ip address add address={{ item.gateway_ip }} interface={{ item.name }}"
  register: add_address_results
  failed_when: "'failure' in add_address_results.stdout[0]"
  when: get_address_results.stdout[0].find("address="+item.gateway_ip+" ") == -1
  changed_when: true


- name: Get list of networks
  community.network.routeros_command:
    commands: "/routing ospf network export"
  register: get_ospf_network_results

- name: Add the network to OSPF
  community.network.routeros_command:
    commands: "/routing ospf network add area=backbone network={{ item.network }}"
  register: add_ospf_network_results
  when: get_ospf_network_results.stdout[0].find("network="+item.network) == -1
  changed_when: true

# TODO: make this handle registering changes in ansible
# TODO: make this not remove the port every time
- name: Remove and add ports to bridge
  community.network.routeros_command:
    commands:
      - "/interface bridge port remove [find interface={{ inner_item }}]"
      - "/interface bridge port add bridge={{ item.name }} interface={{ inner_item }}"
  loop: "{{ item.bridge_ports }}"
  loop_control:
    loop_var: inner_item
  register: remove_and_add_port_results
